In [458]:
import tensorflow as tf
from tensorflow import keras
import numpy as np


    

In [459]:
import sklearn
from sklearn.preprocessing import LabelEncoder
categories = ['unverified', 'non-rumor','true', 'false' ]
label = LabelEncoder()
indices = label.fit_transform(categories)


In [460]:
depth = 4
label = tf.one_hot(indices, depth, on_value=1, off_value=0)

In [461]:
twdict = {}
for c in range(len(categories)):
    twdict[categories[c]]= label[c]
print(twdict)
    

{'unverified': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 0, 1])>, 'non-rumor': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 0, 0])>, 'true': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 1, 0])>, 'false': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 0, 0, 0])>}


In [462]:
print(label)

tf.Tensor(
[[0 0 0 1]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]], shape=(4, 4), dtype=int32)


In [463]:
import os

In [494]:
f = open('label.txt', 'r')
label_tweet = {}
for c in f.readlines():
    val = c.split(':')
    label_tweet[val[1][:-3]] = twdict[val[0]]

print(label_tweet)


  

    

{'7311663993899622': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 0, 1])>, '7145986418272460': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 0, 1])>, '6918090043565015': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 0, 0])>, '6932047089331609': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 0, 0])>, '5510996917029560': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 1, 0])>, '7672237740726763': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 0, 0])>, '7155159825848811': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 0, 1])>, '5141062738521743': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 1, 0])>, '5003198013449297': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 0, 1])>, '4953666188188303': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 0, 0, 0])>, '5322069107964682': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 0, 0, 0])>, '5601879703898193': <tf.Tensor: shape=(4,), dtype=int32, numpy=a

In [469]:
import json
with open('U1.json') as f:
    user_data = json.load(f)
with open('U2.json') as f:
    user_data.update(json.load(f))
for c in user_data:
    t=(user_data[c])
    if(t[7]):
        t[7]=1;
    else:
        t[7]=0;
        
    if(t[6]):
        t[6]=1;
    else:
        t[6]=0;

# print(user_data['21061006'])
        

        

In [470]:
model = tf.keras.Sequential([
        tf.keras.layers.LSTM(32, return_sequences=False, dropout=0.1, recurrent_dropout=0.1),
        tf.keras.layers.Conv2D(32,(3,3), activation = 'relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Conv2D(16, (3,3), activation = 'relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(4, activation = 'relu'),
        ])
        
        
from tensorflow.keras.optimizers import SGD
model.compile(optimizer = SGD(lr = 0.05),
             loss = 'categorical_crossentropy',
             metrics= ['accuracy'])

In [471]:
import os
datadir = os.getcwd()
print(datadir)
datadir = os.path.join(datadir, 'tree')
print(datadir)
file_list = os.listdir(datadir)
for file in file_list:
    twfile = os.path.join(datadir, file)
    file_data=open(twfile,'r')
    for data in file_data.readlines():
        val = list(data.split('->'))

    
    
    

C:\Users\Yuvi\Desktop\Data Science 20
C:\Users\Yuvi\Desktop\Data Science 20\tree


In [473]:
f = open('A1.txt', 'r',encoding='utf-8')
source_tweet = {}
for c in f.readlines():
    source_tweet[(c[:18]).strip()] = c[18:].strip()
f = open('A2.txt', 'r',encoding='utf-8')

for c in f.readlines():
    source_tweet[(c[:18]).strip()] = c[18:].strip()


In [474]:
datadir = os.getcwd()
print(datadir)
datadir = os.path.join(datadir, 'tree')
open

C:\Users\Yuvi\Desktop\Data Science 20


<function io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)>

In [475]:
import os
p_path = {}

adir = os.getcwd()
datadir = os.path.join(adir, 'tree')
for files in os.listdir(datadir):
    list_path = []
    x = 0
    file_data=open(os.path.join(datadir, files),'r')
    for data in file_data.readlines():
        val = data.split('->')
        f = os.path.join(datadir, files)
        f = os.path.splitext(f)[0]
        f = f[43:]
        split=val[1].split(',')
        split[2] = split[2][:-2]
        list_path.append([split[0][2:-1], split[2].strip()[1:-1]])
        x+=1
        if x==40 :
            break;
    p_path[f] = list_path  
    for c in p_path[f]:
        if isinstance(c[0],type(str)) == True:
            if(user_data.get(c[0],0) != 0):
                c[0] = user_data[c[0]]
            else:
                c[0] = [-1, -1,-1,-1,-1,-1,-1,-1]
        else:
            c[0] = [-1, -1,-1,-1,-1,-1,-1,-1]
            
    print(p_path[f])
                

    
       
      

[[[74, 13, 12229005, 5099, 69538, 10.6849, 1, 1], '0.0'], [[-1, -1, -1, -1, -1, -1, -1, -1], '0.45'], [[-1, -1, -1, -1, -1, -1, -1, -1], '0.85'], [[2, 7, 1766, 249, 21554, 10.7014, 0, 1], '1.15'], [[61, 15, 87, 892, 1937, 10.8795, 0, 0], '1.2'], [[133, 12, 1566, 3200, 73231, 10.0658, 0, 1], '1.4'], [[74, 10, 127, 169, 5067, 9.2877, 0, 1], '1.5'], [[37, 9, 138, 1548, 19888, 10.8164, 0, 1], '1.53'], [[-1, -1, -1, -1, -1, -1, -1, -1], '2.05'], [[16, 13, 84, 247, 13536, 10.4055, 0, 1], '2.1'], [[14, 10, 80, 103, 3021, 9.7397, 0, 0], '2.12'], [[0, 11, 86, 2129, 31, 9.3096, 0, 1], '2.17'], [[152, 13, 47, 306, 1409, 7.2493, 0, 0], '2.18'], [[145, 8, 21, 129, 395, 8.0932, 0, 0], '2.57'], [[75, 7, 81, 725, 6842, 8.9397, 0, 0], '2.75'], [[37, 13, 37, 673, 2919, 10.789, 0, 0], '2.87'], [[155, 14, 1115, 1072, 37133, 10.8164, 0, 0], '3.27'], [[61, 8, 52, 52, 8003, 7.6521, 0, 1], '3.38'], [[82, 12, 583, 971, 5084, 10.8356, 0, 1], '3.62'], [[-1, -1, -1, -1, -1, -1, -1, -1], '3.75'], [[-1, -1, -1, -1,

[[[0, 8, 329, 315, 7241, 7.463, 0, 1], '0.0'], [[4, 10, 297, 186, 506, 6.2685, 0, 0], '5.13'], [[15, 7, 1475, 860, 83720, 7.4548, 0, 1], '5.13'], [[16, 12, 237, 0, 8299, 6.7178, 0, 1], '5.13'], [[14, 10, 525, 445, 10684, 7.4247, 0, 0], '5.13'], [[-1, -1, -1, -1, -1, -1, -1, -1], '5.13'], [[-1, -1, -1, -1, -1, -1, -1, -1], '5.13'], [[27, 7, 534, 562, 30951, 6.737, 0, 1], '5.13'], [[0, 9, 1058, 554, 22015, 8.4027, 0, 1], '5.13'], [[70, 9, 739, 426, 34970, 7.0575, 0, 1], '5.45'], [[0, 10, 43, 249, 71, 6.2055, 0, 0], '6.25'], [[0, 14, 648, 0, 16229, 6.7562, 0, 0], '7.43'], [[66, 7, 353, 268, 82979, 8.0301, 0, 1], '8.93'], [[106, 7, 69, 82, 1578, 8.8548, 0, 0], '9.65'], [[8, 8, 471, 519, 11200, 7.1699, 0, 1], '12.5'], [[129, 9, 232, 484, 15256, 9.1808, 0, 1], '13.97'], [[107, 9, 299, 317, 16216, 7.7863, 0, 0], '14.62'], [[8, 8, 1831, 780, 207067, 8.6548, 0, 1], '16.95'], [[35, 7, 515, 1090, 15730, 9.7753, 0, 1], '17.42'], [[-1, -1, -1, -1, -1, -1, -1, -1], '18.43'], [[-1, -1, -1, -1, -1, -1

[[[147, 6, 204490, 2345, 117892, 11.6356, 1, 1], '0.0'], [[132, 8, 1004, 1549, 134927, 9.8685, 0, 0], '0.33'], [[163, 14, 22117, 975, 103879, 10.6438, 0, 1], '0.45'], [[25, 13, 1247, 806, 93156, 8.1699, 0, 1], '2.6'], [[145, 9, 11276, 931, 107831, 10.3151, 0, 1], '2.6'], [[63, 11, 8318, 6486, 205472, 8.5315, 0, 0], '2.6'], [[0, 13, 940, 2153, 239652, 10.4274, 0, 0], '2.6'], [[0, 12, 520, 2452, 104195, 7.6438, 0, 0], '2.6'], [[134, 13, 2098, 1455, 132058, 9.2438, 0, 1], '2.6'], [[-1, -1, -1, -1, -1, -1, -1, -1], '2.6'], [[146, 13, 13262, 875, 19381, 10.0055, 1, 0], '2.6'], [[43, 12, 355, 536, 9964, 8.2274, 0, 0], '2.6'], [[0, 8, 11, 47, 2379, 7.9562, 0, 0], '2.6'], [[146, 10, 493, 1948, 13768, 11.2877, 0, 1], '2.6'], [[-1, -1, -1, -1, -1, -1, -1, -1], '2.6'], [[140, 7, 775, 721, 12742, 9.7726, 0, 0], '2.6'], [[0, 10, 61, 128, 5153, 6.4959, 0, 0], '2.6'], [[139, 9, 1473, 1304, 257044, 6.1836, 0, 1], '2.6'], [[160, 8, 2032, 3559, 35444, 9.5178, 0, 0], '2.6'], [[157, 14, 7291, 2481, 437125

[[[140, 3, 216685, 8352, 63580, 8.7041, 0, 1], '0.0'], [[7, 5, 3300, 849, 60200, 8.9096, 0, 1], '0.73'], [[-1, -1, -1, -1, -1, -1, -1, -1], '0.93'], [[48, 10, 1086, 675, 39177, 10.7726, 0, 0], '1.17'], [[69, 7, 2290, 2232, 54234, 9.3041, 0, 1], '1.22'], [[67, 10, 1162, 3597, 73686, 10.9589, 0, 1], '2.75'], [[-1, -1, -1, -1, -1, -1, -1, -1], '2.75'], [[53, 15, 194, 347, 50812, 6.7288, 0, 1], '2.75'], [[0, 7, 1605, 310, 5959, 7.0, 0, 0], '2.75'], [[12, 8, 1025, 904, 8305, 7.7507, 0, 1], '2.75'], [[138, 5, 1041, 366, 96283, 9.3205, 0, 1], '2.75'], [[-1, -1, -1, -1, -1, -1, -1, -1], '2.75'], [[31, 10, 1553, 3752, 54204, 8.389, 0, 0], '2.75'], [[132, 11, 491, 1540, 14425, 6.3699, 0, 1], '2.75'], [[47, 11, 252, 705, 17533, 8.3589, 0, 1], '2.75'], [[144, 13, 5204, 5467, 50575, 10.6548, 0, 0], '2.75'], [[88, 14, 804, 240, 77436, 9.2904, 0, 1], '2.75'], [[149, 9, 598, 638, 28704, 11.1616, 0, 1], '2.75'], [[63, 6, 386, 1815, 8871, 7.5644, 0, 0], '2.75'], [[25, 8, 231, 1041, 8290, 8.9699, 0, 1], 

[[[154, 4, 711902, 1352, 372939, 11.4384, 1, 0], '0.0'], [[110, 9, 1286, 971, 68709, 8.6795, 0, 1], '4.08'], [[84, 11, 723, 302, 71872, 7.9096, 0, 1], '5.63'], [[15, 15, 548, 353, 20095, 6.7205, 0, 1], '5.82'], [[26, 12, 1003, 510, 46103, 6.2877, 0, 1], '6.32'], [[149, 11, 1568, 4560, 11160, 9.8493, 0, 1], '6.98'], [[-1, -1, -1, -1, -1, -1, -1, -1], '7.08'], [[5, 9, 547, 3679, 29135, 6.9315, 0, 1], '7.08'], [[26, 12, 1003, 510, 46103, 6.2877, 0, 1], '6.32'], [[-1, -1, -1, -1, -1, -1, -1, -1], '7.08'], [[128, 15, 827, 801, 62392, 9.263, 0, 1], '7.08'], [[38, 10, 930, 376, 59186, 7.5699, 0, 1], '7.08'], [[19, 13, 604, 548, 30145, 5.6027, 0, 1], '7.08'], [[6, 7, 188, 188, 27827, 6.9753, 0, 1], '7.08'], [[6, 7, 308, 124, 73667, 11.0877, 0, 0], '7.08'], [[2, 13, 513, 277, 23557, 7.8137, 0, 1], '7.08'], [[159, 15, 24912, 601, 143825, 8.5288, 0, 1], '7.08'], [[78, 11, 1501, 143, 9899, 10.7096, 0, 1], '7.08'], [[0, 8, 132, 0, 9019, 5.937, 0, 1], '7.08'], [[18, 12, 780, 957, 70328, 10.7699, 0, 

[[[101, 9, 1041, 746, 3725, 10.8384, 0, 1], '0.0'], [[35, 10, 449, 1365, 9495, 10.2466, 0, 0], '1.17'], [[149, 9, 50396, 3895, 93321, 11.9836, 1, 1], '1.17'], [[125, 3, 3581, 1981, 58622, 12.8466, 0, 1], '1.17'], [[45, 10, 5735, 937, 5921, 8.3452, 0, 1], '1.4'], [[-1, -1, -1, -1, -1, -1, -1, -1], '1.52'], [[0, 13, 13, 105, 54, 8.9973, 0, 0], '1.63'], [[93, 12, 1285, 1677, 3079, 10.5041, 0, 0], '1.67'], [[124, 6, 55, 127, 748, 10.7808, 0, 1], '1.88'], [[18, 14, 294, 619, 2556, 9.4219, 0, 1], '2.7'], [[80, 15, 1536, 2463, 45053, 7.2055, 0, 1], '3.11'], [[103, 8, 23177, 1726, 449, 13.1507, 1, 0], '3.31'], [[147, 15, 28560, 27280, 52863, 6.3945, 0, 1], '3.41'], [[0, 8, 70, 333, 864, 7.874, 0, 1], '3.52'], [[156, 12, 607, 900, 5279, 10.989, 0, 1], '3.67'], [[74, 13, 1190, 1735, 24712, 10.3589, 0, 1], '3.74'], [[114, 15, 210, 664, 3417, 6.2192, 0, 0], '3.82'], [[155, 9, 23242, 12512, 124912, 5.9644, 0, 0], '4.02'], [[0, 8, 468, 614, 9713, 7.5589, 0, 0], '4.22'], [[159, 8, 3921, 4981, 14547, 

[[[44, 2, 6651579, 5869, 243487, 11.3342, 1, 1], '0.0'], [[154, 12, 275, 1076, 2091, 6.7863, 0, 0], '0.33'], [[148, 10, 1266, 376, 94740, 5.4767, 0, 0], '0.33'], [[57, 7, 167, 859, 10712, 9.1479, 0, 1], '0.76'], [[127, 14, 2199, 1295, 147665, 11.3616, 0, 1], '0.97'], [[73, 4, 12040, 3543, 95448, 12.2274, 0, 0], '1.08'], [[139, 15, 12875, 974, 234726, 5.811, 0, 0], '1.13'], [[27, 12, 18464, 1445, 5430, 9.074, 0, 0], '1.16'], [[131, 15, 1816, 832, 3596, 7.7425, 0, 1], '1.18'], [[-1, -1, -1, -1, -1, -1, -1, -1], '1.3'], [[10, 9, 41, 125, 1404, 7.5589, 0, 0], '1.42'], [[118, 10, 664, 845, 92495, 10.8548, 0, 0], '2.17'], [[56, 11, 789, 883, 36408, 6.8932, 0, 0], '2.55'], [[71, 13, 384, 796, 20497, 7.6192, 0, 0], '2.74'], [[156, 13, 8914, 6808, 169761, 11.0685, 0, 1], '2.84'], [[150, 10, 1199, 1377, 13063, 8.3726, 0, 1], '2.89'], [[30, 2, 775, 434, 34055, 10.7753, 0, 1], '2.91'], [[138, 10, 555, 2138, 18001, 8.9836, 0, 1], '2.92'], [[111, 9, 63, 155, 1607, 8.8301, 0, 1], '2.93'], [[130, 15, 

[[[140, 3, 216685, 8352, 63580, 8.7041, 0, 1], '0.0'], [[38, 6, 320, 1078, 12650, 10.874, 0, 1], '0.13'], [[-1, -1, -1, -1, -1, -1, -1, -1], '0.17'], [[155, 9, 322, 771, 55587, 10.7068, 0, 1], '0.17'], [[95, 7, 984, 748, 44550, 8.7479, 0, 1], '0.18'], [[97, 8, 2180, 3031, 265569, 10.1041, 0, 0], '0.22'], [[157, 14, 3979, 4955, 907839, 10.9863, 0, 1], '0.23'], [[-1, -1, -1, -1, -1, -1, -1, -1], '0.23'], [[113, 7, 2126, 2310, 65570, 8.8493, 0, 1], '0.37'], [[23, 10, 600, 634, 101933, 9.5507, 0, 1], '0.42'], [[69, 13, 836, 906, 94568, 10.4685, 0, 1], '0.42'], [[0, 12, 550, 196, 37, 7.6466, 0, 0], '0.42'], [[0, 11, 631, 2090, 43032, 10.2301, 0, 0], '0.43'], [[76, 10, 178, 607, 5290, 10.3288, 0, 1], '0.43'], [[0, 11, 400, 416, 52134, 10.2466, 0, 1], '0.48'], [[-1, -1, -1, -1, -1, -1, -1, -1], '0.51'], [[-1, -1, -1, -1, -1, -1, -1, -1], '0.52'], [[138, 12, 132651, 1783, 180496, 11.6438, 1, 1], '0.53'], [[137, 15, 6247, 6084, 184339, 7.263, 0, 0], '0.53'], [[22, 10, 529, 558, 67627, 7.0685, 0

[[[160, 2, 13693086, 7079, 257831, 10.5562, 1, 0], '0.0'], [[160, 12, 12927, 2650, 133047, 9.4548, 0, 1], '0.22'], [[-1, -1, -1, -1, -1, -1, -1, -1], '0.22'], [[0, 7, 270, 205, 23670, 8.3342, 0, 1], '0.23'], [[128, 12, 2117, 750, 125061, 7.9178, 0, 0], '0.25'], [[87, 12, 731, 3105, 18612, 9.5644, 0, 1], '0.27'], [[25, 9, 1322, 1, 149575, 12.1178, 0, 0], '0.32'], [[-1, -1, -1, -1, -1, -1, -1, -1], '0.32'], [[0, 8, 36, 212, 1837, 5.4493, 0, 0], '0.32'], [[126, 10, 1244, 2108, 55405, 7.2466, 0, 1], '0.42'], [[16, 14, 785, 2189, 140820, 8.9479, 0, 1], '0.43'], [[0, 15, 396, 256, 137996, 5.6822, 0, 0], '0.43'], [[53, 8, 998, 1630, 3046, 6.189, 0, 0], '0.45'], [[-1, -1, -1, -1, -1, -1, -1, -1], '0.47'], [[158, 9, 24378, 1129, 11464, 11.1205, 0, 0], '0.47'], [[-1, -1, -1, -1, -1, -1, -1, -1], '0.47'], [[15, 9, 387, 647, 1412, 5.9808, 0, 1], '0.5'], [[87, 10, 574, 464, 2149, 6.5973, 0, 0], '0.5'], [[120, 15, 3166, 4951, 41284, 10.7178, 0, 0], '0.5'], [[105, 13, 3604, 4408, 243547, 9.7288, 0, 1

[[[129, 8, 3413340, 508, 227258, 12.8027, 1, 0], '0.0'], [[151, 13, 796, 1577, 38058, 7.2521, 0, 1], '0.72'], [[90, 15, 557, 549, 8407, 5.589, 0, 1], '0.72'], [[143, 8, 190, 629, 1538, 8.7945, 0, 1], '0.72'], [[-1, -1, -1, -1, -1, -1, -1, -1], '0.73'], [[0, 11, 151, 500, 4865, 6.3918, 0, 1], '1.32'], [[98, 12, 76, 154, 4820, 10.5836, 0, 0], '1.62'], [[139, 5, 2000, 1977, 7817, 10.7151, 0, 1], '1.77'], [[0, 13, 134, 151, 61271, 10.4192, 0, 1], '1.84'], [[159, 8, 11956, 3702, 165135, 10.7233, 0, 0], '1.88'], [[72, 14, 80, 418, 1844, 10.6986, 0, 0], '1.92'], [[-1, -1, -1, -1, -1, -1, -1, -1], '1.97'], [[160, 13, 3363, 3036, 211124, 4.6192, 0, 0], '1.98'], [[147, 8, 307, 462, 2533, 10.7151, 0, 1], '2.02'], [[4, 12, 66, 170, 248, 6.9918, 0, 0], '2.07'], [[0, 10, 46, 1752, 2241, 10.6575, 0, 1], '2.37'], [[98, 7, 819, 1858, 98167, 5.8712, 0, 1], '2.71'], [[111, 12, 1884, 3177, 281235, 8.1096, 0, 0], '2.88'], [[100, 12, 2708, 3115, 35660, 11.811, 0, 1], '2.96'], [[122, 8, 6390, 3131, 39671, 10

[[[-1, -1, -1, -1, -1, -1, -1, -1], '0.0'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[90, 12, 7141, 576, 18529, 4.989, 0, 0], '150.58'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[97, 14, 16828, 0, 18021, 4.9945, 0, 0], '150.58'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[-1, -1, -1, -1, -1, -1, -1, -1], '150.58'], [[99, 13, 5563, 0, 8239, 4.9589, 0, 0], '150.58'], [[-1, -1, -1, -1,

[[[-1, -1, -1, -1, -1, -1, -1, -1], '0.0'], [[83, 12, 528, 790, 13187, 10.6548, 0, 1], '0.55'], [[120, 11, 4620, 4322, 23846, 7.3781, 0, 1], '0.55'], [[-1, -1, -1, -1, -1, -1, -1, -1], '0.55'], [[114, 7, 852, 2644, 8381, 8.874, 0, 0], '0.78'], [[152, 8, 4124, 4990, 122840, 10.2356, 0, 0], '0.9'], [[54, 8, 209, 345, 16454, 4.5178, 0, 1], '0.93'], [[157, 13, 516, 377, 72441, 5.5836, 0, 1], '0.96'], [[77, 11, 581, 594, 11690, 5.0466, 0, 0], '1.02'], [[156, 12, 2544, 3145, 72316, 6.5699, 0, 0], '1.12'], [[144, 15, 1728, 1190, 33485, 6.5205, 0, 0], '1.18'], [[54, 14, 712, 1213, 15288, 7.3781, 0, 1], '1.22'], [[145, 13, 1726, 3644, 16573, 10.1918, 0, 1], '1.28'], [[-1, -1, -1, -1, -1, -1, -1, -1], '2.0'], [[36, 7, 794, 1578, 57270, 5.2247, 0, 0], '2.1'], [[144, 9, 1412, 3057, 39751, 11.3863, 0, 1], '2.37'], [[0, 8, 95, 251, 9651, 4.4411, 0, 1], '2.47'], [[-1, -1, -1, -1, -1, -1, -1, -1], '2.55'], [[-1, -1, -1, -1, -1, -1, -1, -1], '2.57'], [[106, 10, 723, 862, 15510, 7.4795, 0, 0], '2.83'], 

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [476]:
print(len(p_path['552791578893619200']))



40


In [478]:
x = 0
for keys in p_path:
    p_key = p_path[keys]
p_key = np.array

[[[74, 13, 12229005, 5099, 69538, 10.6849, 1, 1], '0.0'], [[-1, -1, -1, -1, -1, -1, -1, -1], '0.45'], [[-1, -1, -1, -1, -1, -1, -1, -1], '0.85'], [[2, 7, 1766, 249, 21554, 10.7014, 0, 1], '1.15'], [[61, 15, 87, 892, 1937, 10.8795, 0, 0], '1.2'], [[133, 12, 1566, 3200, 73231, 10.0658, 0, 1], '1.4'], [[74, 10, 127, 169, 5067, 9.2877, 0, 1], '1.5'], [[37, 9, 138, 1548, 19888, 10.8164, 0, 1], '1.53'], [[-1, -1, -1, -1, -1, -1, -1, -1], '2.05'], [[16, 13, 84, 247, 13536, 10.4055, 0, 1], '2.1'], [[14, 10, 80, 103, 3021, 9.7397, 0, 0], '2.12'], [[0, 11, 86, 2129, 31, 9.3096, 0, 1], '2.17'], [[152, 13, 47, 306, 1409, 7.2493, 0, 0], '2.18'], [[145, 8, 21, 129, 395, 8.0932, 0, 0], '2.57'], [[75, 7, 81, 725, 6842, 8.9397, 0, 0], '2.75'], [[37, 13, 37, 673, 2919, 10.789, 0, 0], '2.87'], [[155, 14, 1115, 1072, 37133, 10.8164, 0, 0], '3.27'], [[61, 8, 52, 52, 8003, 7.6521, 0, 1], '3.38'], [[82, 12, 583, 971, 5084, 10.8356, 0, 1], '3.62'], [[-1, -1, -1, -1, -1, -1, -1, -1], '3.75'], [[-1, -1, -1, -1,

In [500]:
import numpy as np
# print(label_tweet)
train = 
label=sorted(label_tweet)
for c in label:
    train[c] = label_tweet[c]
print(label)
x = np.array(label_tw)
y = np.array(p_path.values())
model.fit(x, y, epochs = 5)

['2659532852472094', '2731825682984509', '2732787619092398', '2951522879014174', '2959441379481518', '3182632940980305', '3191666369029980', '3261372854500188', '3347220030576476', '3368737592711577', '3369136569210839', '3482038187412725', '3482044266595082', '3482099985658798', '3517673440973987', '3520756725434286', '3562689802116874', '3562970801694474', '3563104693902458', '3564071059530711', '3564379416414167', '3572998790700236', '3573004092929597', '3585910894620999', '3643834575451627', '3645896965731246', '3650521553857495', '3650568364764815', '3652762063812689', '3654970160983695', '3660257661835141', '3662052975571107', '3695060081727406', '3708555960501084', '3724891529036431', '3729012601834946', '3729149761028341', '3768742736016302', '3769825391323668', '3770022322578554', '3775194455788953', '3800551728962723', '3801401145521889', '3866821638629867', '3869980380041134', '3870065531248967', '3870067006092288', '3870071206897377', '3870095777633607', '3870102995363553',

IndexError: tuple index out of range

In [ ]:
for label in 